version: '3'
services:
  web:
    build: ./
    command: tail -f /dev/null
    #    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      # ruby-debug-ide 用
      - "1234:1234"
      - "26162:26162"
      # rails用
      - "${DOCKER_WEB_HOST_PORT}:${DOCKER_WEB_CONTAINER_PORT}"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/record_wod
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres@db:${DOCKER_DB_CONTAINER_PORT}"
    tty: true
    stdin_open: true
  db:
    image: postgres:12.2
    ports:
      - "${DOCKER_DB_HOST_PORT}:${DOCKER_DB_CONTAINER_PORT}"
    environment:
      POSTGRES_DB: record_wod_development
      POSTGRES_HOST_AUTH_METHOD: trust
